name: Publish Mastodon status if new blog is available
on:
  schedule:
    - cron: "0 9 * * *"
jobs:
  publish:
    environment:
      name: mastodon-poster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Install jq'
        uses: dcarbone/install-jq-action@v1.0.1
      - name: 'Install hq'
        run: |
          _version='1.0.1'
          # Probably this is the right arch right?
          _dl_url="https://github.com/orf/hq/releases/download/v$_version/hq-Linux-x86_64.tar.gz"
          _dl_path="$RUNNER_TEMP/jq"
          wget -O- "${_dl_url}" > "${_dl_path}"

          echo "Creating tool cache directory $RUNNER_TOOL_CACHE/jq"
          mkdir -p "$RUNNER_TOOL_CACHE/jq"

          echo "Installing into tool cache:"
          echo "Src: $_dl_path"
          echo "Dst: $RUNNER_TOOL_CACHE/jq/jq"
          mv "$_dl_path" "$RUNNER_TOOL_CACHE/jq/jq"

          chmod +x "$RUNNER_TOOL_CACHE/jq/jq"

          echo "Adding $RUNNER_TOOL_CACHE/jq to path..."
          echo "$RUNNER_TOOL_CACHE/jq" >> $GITHUB_PATH
      - name: 'Run publish script'
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_DOMAIN: https://hachyderm.io
        run: bash ./scripts/publish.sh
          ./scripts/publish.sh

